apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploymentexpress
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express
  template:
    metadata:
      labels:
        app: express
    spec:
      containers:
      - name: express
        image: atoa-web
        ports:
        - containerPort: 3000
        resources:
          requests:
            cpu: "250m"
